config/routes.rb
Rails.application.routes.draw do
  resources :posts
  resources :high_schools
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/high_school.rb
class HighSchool < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/high_schools_controller.rb
class HighSchoolsController < ApplicationController
  before_action :set_high_school, only: [:show, :edit, :update, :destroy]

  # GET /high_schools
  # GET /high_schools.json
  def index
    @high_schools = HighSchool.all
  end

  # GET /high_schools/1
  # GET /high_schools/1.json
  def show
  end

  # GET /high_schools/new
  def new
    @high_school = HighSchool.new
  end

  # GET /high_schools/1/edit
  def edit
  end

  # POST /high_schools
  # POST /high_schools.json
  def create
    @high_school = HighSchool.new(high_school_params)

    respond_to do |format|
      if @high_school.save
        format.html { redirect_to @high_school, notice: 'High school was successfully created.' }
        format.json { render :show, status: :created, location: @high_school }
      else
        format.html { render :new }
        format.json { render json: @high_school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /high_schools/1
  # PATCH/PUT /high_schools/1.json
  def update
    respond_to do |format|
      if @high_school.update(high_school_params)
        format.html { redirect_to @high_school, notice: 'High school was successfully updated.' }
        format.json { render :show, status: :ok, location: @high_school }
      else
        format.html { render :edit }
        format.json { render json: @high_school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /high_schools/1
  # DELETE /high_schools/1.json
  def destroy
    @high_school.destroy
    respond_to do |format|
      format.html { redirect_to high_schools_url, notice: 'High school was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_high_school
      @high_school = HighSchool.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def high_school_params
      params.require(:high_school).permit(:game, :score)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.fetch(:post, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/high_schools_helper.rb
module HighSchoolsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/high_schools/_form.html.erb
<%= form_with(model: high_school, local: true) do |form| %>
  <% if high_school.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(high_school.errors.count, "error") %> prohibited this high_school from being saved:</h2>

      <ul>
      <% high_school.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :game %>
    <%= form.text_field :game, id: :high_school_game %>
  </div>

  <div class="field">
    <%= form.label :score %>
    <%= form.number_field :score, id: :high_school_score %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/high_schools/edit.html.erb
<h1>Editing High School</h1>

<%= render 'form', high_school: @high_school %>

<%= link_to 'Show', @high_school %> |
<%= link_to 'Back', high_schools_path %>

app/views/high_schools/index.html.erb
<p id="notice"><%= notice %></p>

<h1>High Schools</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Score</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @high_schools.each do |high_school| %>
      <tr>
        <td><%= high_school.game %></td>
        <td><%= high_school.score %></td>
        <td><%= link_to 'Show', high_school %></td>
        <td><%= link_to 'Edit', edit_high_school_path(high_school) %></td>
        <td><%= link_to 'Destroy', high_school, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New High School', new_high_school_path %>

app/views/high_schools/new.html.erb
<h1>New High School</h1>

<%= render 'form', high_school: @high_school %>

<%= link_to 'Back', high_schools_path %>

app/views/high_schools/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @high_school.game %>
</p>

<p>
  <strong>Score:</strong>
  <%= @high_school.score %>
</p>

<%= link_to 'Edit', edit_high_school_path(@high_school) %> |
<%= link_to 'Back', high_schools_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>March</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>